# Generated by Django 6.0.2 on 2026-02-23 18:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('material', models.CharField(choices=[('GOLD', 'Gold'), ('SILV', 'Silver'), ('BRNZ', 'Bronze'), ('IRON', 'Iron'), ('COPP', 'Copper'), ('LEAD', 'Lead'), ('MARB', 'Marble'), ('LIME', 'Limestone'), ('FLNT', 'Flint'), ('OBSD', 'Obsidian'), ('SAND', 'Sandstone'), ('GRAN', 'Granite'), ('CERA', 'Ceramic'), ('GLAS', 'Glass'), ('FAIE', 'Faience'), ('BONE', 'Bone'), ('WOOD', 'Wood'), ('LETH', 'Leather'), ('TEXT', 'Textile'), ('PAPR', 'Paper'), ('PLAS', 'Plaster'), ('MIXD', 'Mixed Materials'), ('UNKN', 'Unknown / Unidentified')], default='UNKN', max_length=10)),
                ('found_at_site', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='categories.category')),
            ],
        ),
    ]
