# Generated by Django 6.0.2 on 2026-02-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PRE', 'Prehistoric'), ('THRA', 'Thracian Period'), ('ROMN', 'Roman & Late Antiquity'), ('EMP1', 'First Bulgarian Empire (681–1018)'), ('BYZ', 'Byzantine Period'), ('EMP2', 'Second Bulgarian Empire (1185–1396)'), ('OTTM', 'Ottoman Period'), ('MODR', 'Modern/Recent (Post-1878)')], help_text='Select the historical era.', max_length=4)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
