# Generated by Django 6.0.2 on 2026-02-23 18:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artifacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreservationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField(help_text='The date this specific inspection took place.')),
                ('condition', models.CharField(choices=[('EXC', 'Excellent (Stable, no degradation)'), ('GOOD', 'Good (Minor wear, currently stable)'), ('FAIR', 'Fair (Showing signs of deterioration, needs monitoring)'), ('POOR', 'Poor (Active degradation, intervention needed)'), ('CRIT', 'Critical (Immediate restoration required)')], default='GOOD', max_length=4)),
                ('restoration_notes', models.TextField(blank=True)),
                ('current_location', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, message='Location name must be at least 3 characters.')])),
                ('is_on_display', models.BooleanField(default=True)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='artifacts.artifact')),
            ],
            options={
                'ordering': ['-check_date'],
            },
        ),
    ]
